Assembler homework
AdvancerMan/first-term pull request #1
Opened 2020-06-29 15:38 UTC by AdvancerMan

2020-06-29 21:49 UTC, kt-cpp requested changes
В целом используется неприлично много регистров, что путает. Можно явно меньше Адрес второго операнда между итерациями внутреннего цикла можно сохранять на стек, а только в другие регистры

2020-06-29 21:49 UTC, kt-cpp commented on asm/mul.asm
> +long_integer_size: equ          128
[minor] Константы пожалуйста капсом, чтобы они визуально отличались. Если метки обязательно с маленькой, то сделай через дефайн

2020-06-29 21:49 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 2 * long_integer_size * 8
Зачем столько памяти и копии операндов, если ты руками реализуешь умножение в столбик, а не перевызываешь сорокинские функции, которым, да, нужен буфер?

2020-06-29 21:49 UTC, kt-cpp commented on asm/mul.asm
> +                push            rdx  ; higher bits of 32-bit multiply --> carry for next digit
Причём тут 32 бита, если у тебя умножение имеет 128 битный результат в двух регистрах?

2020-07-01 14:44 UTC, AdvancerMan commented on asm/mul.asm
> +                push            rdx  ; higher bits of 32-bit multiply --> carry for next digit
Опечатался --- имеются в виду 64 бита  старших бита после умножения (хранятся в rdx после mul)

2020-07-02 04:50 UTC, AdvancerMan commented on asm/mul.asm
> +long_integer_size: equ          128
Исправил

2020-07-02 06:11 UTC, AdvancerMan commented on asm/mul.asm
> +                mov             r15, r8   ; counter for outer loop * 8
Осознал тут проблему. Сейчас исправлю. (мы хотим сохранить прошлое состояние регистров `rax`, `rdx`, `r8`, но при этом портим другие регистры)

2020-07-02 06:15 UTC, AdvancerMan commented on asm/mul.asm
> +                mov             r15, r8   ; counter for outer loop * 8
Осознал тут проблему. Сейчас исправлю. (мы хотим сохранить прошлое состояние регистров `rax`, `rdx`, `r8`, но при этом портим другие регистры)

2020-07-04 00:17 UTC, kt-cpp approved these changes

2020-07-04 00:18 UTC, merged