Vector homework
AdvancerMan/first-term pull request #2
Opened 2020-06-29 15:40 UTC by AdvancerMan

2020-06-29 20:24 UTC, kt-cpp requested changes
note исправлять абсолютно не обязательно, можешь их зарезолвить после прочтения. остальное нужно фиксить

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +#include <assert.h>
[note] в плюсах стараются не делать include заголовков *.h, если есть пристойная версия. здесь это cassert.

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +#pragma once
[note] обычно пишут include-guard, не все компиляторы поддерживают прагму

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +        ptr[i].~T();
здесь не верный порядок деструкторов. нужен обратный.

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +void destroy_all(T* ptr, size_t size) {
т.к. ты пишешь код в хедере, то эта функция будет торчать у всех, кто инклюдит файл. нужно исправить ее (и copy_and_construct) зону видимости. например засунуть в private твоего вектора. + сделать static

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +    iterator insert(iterator it, T const&); // O(N) weak
на самом деле для erase и insert достаточно перегрузок для const_iterator, от этих стоит избавиться

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +    assert(size_ > 0);
это пример плохого ассерта, так ты можешь сломать работу кода, который пользуется твоей библиотекой. ассерты ставят для проверок внутренних инвариантов.

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +    back().~T();
нужно везде либо геттеры либо переменные, но лучше 2ое

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +    size_t count = end_i - begin_i;
нужен правильный тип для поинтер арифметики -- ptrdiff_t

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +    if (count == 0) {
лучше все таки <=

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +        return const_cast<iterator>(first);
лучше все таки data_ + begin_i, как и сделано чуть ниже

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +        data_[i].~T();
снова не верный порядок деструкторов. чтобы не копипастить ошибки, можно сделать крутую перегрузку для destroy_all

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +    if (data) {
вроде если !data, то size_ = 0. так что иф бесполезен, его тело можно и так выполнять

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +                new(data_ + i) T(data_[i - 1]);
что здесь происходит? почему это не copy_and_construct?

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +        : vector() {
здесь не имеет смысла вызывать дефолтный конструктор, как и бесполезная строчка size_ = 0. можно сразу сделать size_ = v.size(). если что-то пойдет не так, то текущий объект просто не построится

2020-06-29 20:24 UTC, kt-cpp commented on vector/vector.h
> +            destroy_all(dst + skip + 1, i - skip - 1);
я не понимаю, что тут происходит. смотрится странно и не понятно зачем. нужно или объяснить или исправить

2020-07-01 11:58 UTC, AdvancerMan commented on vector/vector.h
> +        : vector() {
На практике Сорокин говорил, что если был вызван другой конструктор, то при исключении вызовется деструктор у вектора. По крайней мере тесты без `: vector()` программа не проходит.

2020-07-01 13:07 UTC, AdvancerMan commented on vector/vector.h
> +            destroy_all(dst + skip + 1, i - skip - 1);
Убрал

2020-07-01 13:12 UTC, AdvancerMan commented on vector/vector.h
> +                new(data_ + i) T(data_[i - 1]);
Переписал

2020-07-01 13:13 UTC, AdvancerMan commented on vector/vector.h
> +        data_[i].~T();
Переписал

2020-07-01 14:04 UTC, AdvancerMan commented on vector/vector.h
> +        : vector() {
size_ = 0 -- бесполезно.
size_ = v.size стоит после копирования, так как (при исключении в copy_and_construct) деструктор вектора хочет вызвать деструкторы элементов 0 = size_ раз, так как мы уже все вызвали в  copy_and_construct

2020-07-01 23:34 UTC, kt-cpp commented on vector/vector.h
> +        copy_and_construct(data_, v.data_, v.size_);
[guarantee] Просят сильную, если в copy бросится что-то, то ты гарантируешь только слабую - капасити и дата поменяются (хоть и будут валидными)

2020-07-01 23:34 UTC, kt-cpp commented on vector/vector.h
> +void destroy_all(T* ptr, size_t size) {
Забыл сделать статическими

2020-07-01 23:36 UTC, kt-cpp commented on vector/vector.h
> +    assert(size_ > 0);
Забыл парочку, но докошмаривать не буд

2020-07-01 23:43 UTC, kt-cpp requested changes

2020-07-01 23:43 UTC, kt-cpp commented on vector/vector.h
>      }
![image](https://user-images.githubusercontent.com/67123994/86301086-5471b400-bc1e-11ea-9bf8-a6bd0702076b.png)
Я ниче не понял, поясни что тут [произошло с последнего раза](https://github.com/AdvancerMan/first-term/pull/2/commits/bda23885be6531b81c85ab4d36bc67f62248bcf0#r447227996), пожалуйста

2020-07-01 23:47 UTC, kt-cpp commented
А еще больше никогда не резолвь комменты сам, пожалуйста

2020-07-02 05:08 UTC, AdvancerMan commented on vector/vector.h
> +void destroy_all(T* ptr, size_t size) {
Переименовал `destroy_all` в `destroy` и сделал статическим. Написал новый `destroy_all`, который вызывает `destroy` для `[data_, data_ + size_)` конкретного вектора, то есть не является статическим. `copy_and_construct` сделал статическим.

2020-07-02 05:10 UTC, AdvancerMan commented on vector/vector.h
> +    if (data) {
Убрал `if`.

2020-07-02 05:27 UTC, AdvancerMan commented on vector/vector.h
> +        copy_and_construct(data_, v.data_, v.size_);
Не очень понятно, что значит сильная гарантия для несозданного вектора. Как уже говорилось ранее, если был вызван другой конструктор, то при исключении вызовется деструктор у вектора. То есть `capacity_` и `data_` перастанут быть валидными. Или они должны остаться как оглашено в дефолтном конструкторе?

2020-07-02 05:38 UTC, AdvancerMan commented on vector/vector.h
>      }
Раньше я сначала вставлял элемент, затем копировал старое содержимое массива в новый, что ломало инвариант порядка вызова конструкторов (конструкторы от начала до конца, деструкторы в обратном порядке).

2020-07-02 05:40 UTC, AdvancerMan commented on vector/vector.h
>      }
Теперь мы создаем по порядку: копируем начало, вставляем элемент, копируем конец. Если где-то бросилось исключение разрушаем все в обратном порядке.

2020-07-02 05:56 UTC, AdvancerMan commented on vector/vector.h
> +                new(data_ + i) T(data_[i - 1]);
Теперь `copy_and_construct` + `splice`

2020-07-02 06:00 UTC, AdvancerMan commented on vector/vector.h
>      }
Сделал попроще через перегрузку `copy_and_construct`.

2020-07-02 06:05 UTC, AdvancerMan commented on vector/vector.h
> +        copy_and_construct(data_, v.data_, v.size_);
(отправил вопрос в таблицу)

2020-07-02 21:44 UTC, kt-cpp requested changes

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +#include <iostream>
[minor] Зачем этот тут?

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
>      typedef T const* const_iterator;
[note] `using`

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    vector<T> splice(const_iterator first);       // O(N) strong
[minor] `<T>` тут не нужно

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    }
Происходит лишнее копирование всех элементов. При отсутствии реаллокаций можно сделать всего одно копирование и `end() - it` свопов. Возможно стоит задуматься над тем стоит ли реализовывать `push_back` или наоборот

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    res.reserve(data_ + size_ - first);
[minorr] `end() - first`?)

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    for (const_iterator it = first; it != data_ + size_; it++) {
[minorr] `end()`?)

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    destroy(const_cast<iterator>(first), data_ + size_);
Почему этот каст корректен?

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::resize(size_t size) {
У обычного вектора есть `resize`, который занимается совсем другими вещами, да и даже у тебя контракт не совпадает с ожиданиями от названия, т.к. не меняет `size_`. Подумай над нейминге

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    size_t cap = capacity_ ? capacity_ * 2 : 1;
[minor] Вместо приведение интегральных типов к `bool`, лучше использовать логические выражения с ними

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +}
У этой функции очень странный контракт, вызванный желанием реализовывать `push_back` через `insert`, верю, что она изменится в последствие

2020-07-02 21:44 UTC, kt-cpp commented on vector/vector.h
> +    operator delete(data);
[note] Лучше без причины не разбрасывать освобождение и удаление по коду и придерживаться правила "кто выделил ресурс, тот его и освобождает", в силу того что принимающая сторона может физически не знать как аллоцировался ресурс. Например невозможно отличить `T*`, выделенный через `operator new` или `operator new[]`

2020-07-03 13:40 UTC, AdvancerMan commented on vector/vector.h
> +    }
Пытаюсь соблюдать инвариант: вызовы конструкторов с начала к концу вектора, а деструкторы в обратном порядке. Если сделать `push_back` элемента, а затем свопать его, то получается вызвали конструктор в середине последним ==> инвариант нарушен. Я что-то неправильно понимаю?

2020-07-05 17:12 UTC, AdvancerMan commented on vector/vector.h
> +#include <iostream>
Видимо что-то импортировал, а потом убрал (iostream иногда для дебага использую). Пофиксил

2020-07-05 17:13 UTC, AdvancerMan commented on vector/vector.h
>      typedef T const* const_iterator;
Исправил

2020-07-05 17:14 UTC, AdvancerMan commented on vector/vector.h
> +    vector<T> splice(const_iterator first);       // O(N) strong
Ок. Пофиксил

2020-07-05 17:17 UTC, AdvancerMan commented on vector/vector.h
> +    res.reserve(data_ + size_ - first);
Исправил

2020-07-05 17:18 UTC, AdvancerMan commented on vector/vector.h
> +    for (const_iterator it = first; it != data_ + size_; it++) {
Исправил

2020-07-05 17:19 UTC, AdvancerMan commented on vector/vector.h
> +void vector<T>::resize(size_t size) {
Исправил

2020-07-05 17:28 UTC, AdvancerMan commented on vector/vector.h
> +    destroy(const_cast<iterator>(first), data_ + size_);
А почему он должен быть некорректен? `iterator` от `const_iterator` отличается только модификатором `const`. Или  тут проблема в том, что `splice` принимает `const_iterator` и затем изменяет массив? Вроде для `erase` и `insert` мы передаем `const_iterator`, но изменяем массив (насколько я понимаю, это сделано, чтобы можно было без `const_cast` или поиска идентичного неконстантного итератора передавать итераторы снаружи в функцию)

2020-07-05 17:28 UTC, AdvancerMan commented on vector/vector.h
> +    size_t cap = capacity_ ? capacity_ * 2 : 1;
Исправил

2020-07-05 17:29 UTC, AdvancerMan commented on vector/vector.h
> +    operator delete(data);
Ок. Исправил

2020-07-05 18:10 UTC, AdvancerMan commented on vector/vector.h
> +}
Исправил

2020-07-05 18:11 UTC, AdvancerMan commented on vector/vector.h
> +    }
Исправил на `swap`, но вопрос еще остался.

2020-07-05 18:40 UTC, kt-cpp commented on vector/vector.h
> +    destroy(const_cast<iterator>(first), data_ + size_);
Вопрос на вопрос отвечать обычно не принято. Вопрос заключается в том, что тебе передали инератор на неизменяемые данные, а ты пытаешься их менять. В общем случае так нельзя делать, и тебе нужно обосновать почему так делать можно

2020-07-05 18:58 UTC, AdvancerMan commented on vector/vector.h
> +    destroy(const_cast<iterator>(first), data_ + size_);
Как я понимаю это делается для следующего случая: какая-то функция вернула нам `const_iterator` для вектора. Нам не хочется ее кастить через `const_cast`, либо получать через `(it - cbegin()) + begin()`. Для этого вектор предлагает нам перегрузки функций с `const_iterator`. Как [выяснилось](https://github.com/AdvancerMan/first-term/pull/2#discussion_r447224116) в этом случае перегрузки для обычных итераторов не нужны

2020-07-06 09:17 UTC, AdvancerMan commented on vector/vector.h
> +    }
Вопрос решили

2020-07-06 15:41 UTC, kt-cpp approved these changes

2020-07-06 15:41 UTC, merged