Biginteger homework
AdvancerMan/first-term pull request #4
Opened 2020-07-01 10:50 UTC by AdvancerMan

2020-07-03 04:03 UTC, kt-cpp requested changes
Код хороший, молодец.
Комментарии, помеченные [note], не обязательны к исправлению.

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.h
> +    static const int INT_T_BITS = sizeof(int_t) * CHAR_BIT;
[minor] `CHAR_BIT` implementation-defined. Нужное количество бит можно получить с помощью `std::numeric_limits`

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.h
> +    static const int_t INT_T_MAX = static_cast<int_t>(-1);
[minor] Не стоит полагаться на представление чисел, когда нужный результат может дать `std::numeric_limits`

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.h
> +    int compare_to(big_integer const&) const;
[minor] Почему эти методы не приватные?

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            a >>= INT_T_BITS;
[note] Я думаю, здесь этот ворнинг допустим. Если бы в задании был стандарт c++17, можно было бы эту конструкцию написать через `if constexpr`.

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if ((std::numeric_limits<int>::digits + 1) % INT_T_BITS != 0) {
[minor] А что будет в случае, если это условие не выполнено? Например, когда int 31-битный. Кажется, ты можешь получить неверный значащий бит в дополнении до двух.

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (size_t i = str[0] == '-' ? 1 : 0; i < str.size(); i++) {
[safety] Что, если строчка пустая?

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        while (i >= size()) {
[performance] `while` в цикле выглядит излишним, все эти действия можно выполнить до начала `for`

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    values.push_back(carry + rest + rhs.get_rest());
[performance] Возможную переаллокацию от этого `push_back` можно заложить в `reserve`

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                             + static_cast<double_int_t>(get(j));
[performance] Метод `get` очень дорогой -- он содержит проверки, которые часто не срабатывают. Это мешает компилятору оптимизировать код. В профайлере `get` тоже достаточно высоко расположен.
Во многих случаях можно напрямую обращаться по индексу в векторе, это сильно ускорит код

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            return {-q, r};
[note] Конструирование кортежа можно ускорить с помощью move-семантики.

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    std::tie(std::ignore, res) = divide(rhs);
[safety] Постарайся, где возможно, обеспечить строгие гарантии исключений.

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator/=(big_integer const& rhs) {
[safety] Не хватает обработки деления на 0

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        values.push_back(get_rest());
[performance] Множество `push_back` подряд будут вызывать ненужные переаллокации вектора

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::int_t myand(big_integer::int_t a, big_integer::int_t b) {
[note] Эти конструкции можно сделать намного лаконичнее с помощью лямбда-выражений

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        values.push_back(get_rest());
[performance] `push_back` в цикле

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            values[i - 1] |= (get(j) & ((int_t(1) << in_block) - 1)) << out_block;
[minor] c-style cast

2020-07-03 04:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    // binary for debug
[minor] Закомментированный без причины код стоит удалять перед релизными коммитами

2020-07-06 13:34 UTC, AdvancerMan commented on bigint/big_integer.h
> +    static const int INT_T_BITS = sizeof(int_t) * CHAR_BIT;
Fixed

2020-07-06 13:37 UTC, AdvancerMan commented on bigint/big_integer.h
> +    static const int_t INT_T_MAX = static_cast<int_t>(-1);
Fixed

2020-07-06 13:41 UTC, AdvancerMan commented on bigint/big_integer.h
> +    int compare_to(big_integer const&) const;
Я считаю, что они будут удобными для пользователя, не считаю что это детали реализации (кажется любая реализация длинного числа может поддержать эти методы без асимптотического увеличения сложности). Также они сохраняют инвариант класса, если им подавать на вход корректный `big_int`.

2020-07-06 13:41 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +            a >>= INT_T_BITS;
Ok

2020-07-06 13:47 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    if ((std::numeric_limits<int>::digits + 1) % INT_T_BITS != 0) {
Возможно тут небольшая путаница с `std::numeric_limits<int>::digits`. По [документации](https://en.cppreference.com/w/cpp/types/numeric_limits/digits) это `CHAR_BIT * sizeof(int) - 1`. То есть для знаковых типов `digits` на 1 меньше, чем количество бит в типе. Тогда для 31-битного инта условие выполнено.

2020-07-06 13:54 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    for (size_t i = str[0] == '-' ? 1 : 0; i < str.size(); i++) {
Добавил проверку на корректность входной строки.

2020-07-06 14:00 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +        while (i >= size()) {
Fixed

2020-07-06 14:01 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    values.push_back(carry + rest + rhs.get_rest());
Fixed

2020-07-06 14:14 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +                             + static_cast<double_int_t>(get(j));
Fixed

2020-07-06 14:23 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +            return {-q, r};
Вроде сделал. Не уверен, что правильно.

2020-07-06 15:05 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +        values.push_back(get_rest());
Fixed

2020-07-06 15:09 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +        values.push_back(get_rest());
Перед циклом написал `reserve`. Надеюсь, что имелось в виду именно это.

2020-07-06 15:09 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +            values[i - 1] |= (get(j) & ((int_t(1) << in_block) - 1)) << out_block;
Fixed

2020-07-06 15:10 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    // binary for debug
Fixed

2020-07-06 15:15 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +big_integer::int_t myand(big_integer::int_t a, big_integer::int_t b) {
Fixed

2020-07-06 15:19 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator/=(big_integer const& rhs) {
Fixed

2020-07-06 15:33 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    std::tie(std::ignore, res) = divide(rhs);
Сделал, но не очень понятно, может ли кинуть ошибку `storage_t::operator[]` или `storage_t::push_back`. Вроде у `int_t` конструктор копирования небросающий.

2020-07-06 16:49 UTC, kt-cpp commented on bigint/big_integer.h
> +    int compare_to(big_integer const&) const;
Хорошо, это имеет смысл

2020-07-06 17:18 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if ((std::numeric_limits<int>::digits + 1) % INT_T_BITS != 0) {
Хорошо, это правда.
Рассмотрим другой случай: по документации `CHAR_BIT` [не меньше 8](https://en.cppreference.com/w/cpp/language/sizeof). Пусть он равен 9 -- тогда `std::numeric_limits<int>::digits` в случае четырёхбайтного инта будет 35. В этом случае выполнится иф, и ты установишь все последние биты у `values.back()` в 1, вне зависимости от того, находится `a` в дополнении до двух или нет.

2020-07-06 17:27 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            return {-q, r};
Для полноценного использования нужно определить [move-constructors](https://en.cppreference.com/w/cpp/language/move_constructor), сейчас это ничем не отличается от копирования объектов.
В любом случае, это тема следующего семестра С++, там всё расскажут подробнее.

2020-07-06 17:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    std::tie(std::ignore, res) = divide(rhs);
Бросает скорее выделение памяти в `push_back`

2020-07-06 17:32 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    if ((std::numeric_limits<int>::digits + 1) % INT_T_BITS != 0) {
Да, согласен. Тогда дополнительным условием в `if` надо поставить `a < 0`. С другой стороны непонятна фраза 
>  находится `a` в дополнении до двух или нет.

Значит ли это, что `int` может хранить число как угодно (Например, [способом со сдвигом](https://neerc.ifmo.ru/wiki/index.php?title=%D0%9F%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D1%86%D0%B5%D0%BB%D1%8B%D1%85_%D1%87%D0%B8%D1%81%D0%B5%D0%BB:_%D0%BF%D1%80%D1%8F%D0%BC%D0%BE%D0%B9_%D0%BA%D0%BE%D0%B4,_%D0%BA%D0%BE%D0%B4_%D1%81%D0%BE_%D1%81%D0%B4%D0%B2%D0%B8%D0%B3%D0%BE%D0%BC,_%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D0%B4))? Если так, то кажется с битами инта работать вообще бесполезно...

2020-07-06 17:36 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +            return {-q, r};
Ок

2020-07-06 17:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        values.push_back(get_rest());
Да, так и есть

2020-07-06 17:41 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if ((std::numeric_limits<int>::digits + 1) % INT_T_BITS != 0) {
Писать кроссплатформенный код сложно(

> Тогда дополнительным условием в if надо поставить a < 0

Добавь, пожалуйста.

> находится a в дополнении до двух или нет.

Этой фразой я имел ввиду, что `a < 0`. Не думаю, что где-то можно наткнуться на числа не в дополнении до двух

2020-07-06 17:44 UTC, kt-cpp requested changes

2020-07-06 17:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (size_t i = str[0] == '-' ? 1 : 0; i < str.size(); i++) {
[minor] Добавь поддержку префиксного `+`

2020-07-06 17:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
[minor] Это можно сократить до `vector::resize`. Подобный код есть ещё в одном месте

2020-07-06 18:17 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    }
Fixed

2020-07-06 18:17 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    for (size_t i = str[0] == '-' ? 1 : 0; i < str.size(); i++) {
Fixed

2020-07-06 18:17 UTC, AdvancerMan commented on bigint/big_integer.cpp
> +    if ((std::numeric_limits<int>::digits + 1) % INT_T_BITS != 0) {
Fixed

2020-07-06 18:23 UTC, kt-cpp approved these changes

2020-07-06 18:24 UTC, merged