Bigint optimized homework
AdvancerMan/first-term pull request #5
Opened 2020-07-06 12:31 UTC by AdvancerMan

Обычный bigint сдал на +-. Чуть позже докину исправления по нему.

2020-07-06 12:50 UTC, AdvancerMan commented
`reserve` не работает на SO, и я не знаю как его реализовать без дополнительной памяти.

2020-07-07 08:33 UTC, AdvancerMan commented
Сдал `bigint` на +. Залил изменения.

2020-07-07 12:59 UTC, kt-cpp requested changes
* Стоит вынести COW класс в отдельный файл
* Глобальная проблема с тем, что ты сжимаешь big в small. Страшна не сама динамическая память, а её выделение. Если уже выделил, то не смысла отдавать просто так

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +// T is trivially constructible, trivially destructible and trivially copiable
[minor] Поставь static_assert на такие требование

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +            buffer* res = reinterpret_cast<buffer*>(operator new(2 * sizeof(size_t) + cap * sizeof(T)));
[minor] `sizeof(buffer) + cap * sizeof(T)`

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +            memcpy(res->values, values, sizeof(T) * std::min(new_cap, capacity));
[minor] `std::copy`

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +            memcpy(res->values, values, sizeof(T) * std::min(new_cap, capacity));
А вообще тут надо смотреть на размер, а не вместимость. Потому что всё, что больше размера формально случайная память

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +    static const size_t SMALL_SIZE = sizeof(buffer*) / sizeof(T);
[minor] `constexpr`

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +    : optimized_storage(size, 0) {}
`T()` мб? Плюс ты нигде не потребовал наличие дефолтного конструктора

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +        memmove(values, other.values, sizeof(T) * size_);
[minor] `std::copy` он справится, что нужно перевызвать

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +        memmove(values, other.values, sizeof(T) * other.size_);
[minor] `std::copy` он справится, что нужно перевызвать

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +        memcpy(tmp->values, values, sizeof(T) * SMALL_SIZE);
[minor] `std::copy`. Я устал искать подобное по коду, найди всё остальное сам

2020-07-07 12:59 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +    back() = e;
Лучше вызывать конструктор копирования, а не оператор присваивания. Второй может отсутствовать при наличие первого

2020-07-07 13:49 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +    : optimized_storage(size, 0) {}
Убрал конструктор от `size_t` (в `bigint` он не нужен)

2020-07-07 14:52 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +            buffer* res = reinterpret_cast<buffer*>(operator new(2 * sizeof(size_t) + cap * sizeof(T)));
Fixed

2020-07-07 14:58 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +// T is trivially constructible, trivially destructible and trivially copiable
Fixed

2020-07-07 15:02 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +    static const size_t SMALL_SIZE = sizeof(buffer*) / sizeof(T);
Fixed

2020-07-07 15:03 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +    back() = e;
Fixed

2020-07-07 15:04 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +    back() = e;
Fixed

2020-07-07 16:18 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +    back() = e;
Fixed

2020-07-07 16:18 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +        memcpy(tmp->values, values, sizeof(T) * SMALL_SIZE);
Fixed

2020-07-07 16:18 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +        memmove(values, other.values, sizeof(T) * other.size_);
Fixed

2020-07-07 16:18 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +        memmove(values, other.values, sizeof(T) * size_);
Fixed

2020-07-07 16:19 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +            memcpy(res->values, values, sizeof(T) * std::min(new_cap, capacity));
Fixed

2020-07-07 16:20 UTC, AdvancerMan commented
> Стоит вынести COW класс в отдельный файл

Fixed

2020-07-07 16:20 UTC, AdvancerMan commented
> Глобальная проблема с тем, что ты сжимаешь big в small. Страшна не сама динамическая память, а её выделение. Если уже выделил, то не смысла отдавать просто так

Fixed

2020-07-07 22:06 UTC, kt-cpp requested changes

2020-07-07 22:06 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +    if (shared.buf->count > 1) {
[minor] Такое условие часто всречается, вынести бы его в отдельную функцию, например, `unique()`

2020-07-07 22:06 UTC, kt-cpp commented on bigint-optimized/optimized_storage.h
> +        T copy(e);
[note] Тут можно выделить случаи, когда эту копию можно не делать. Но так как у тебя всё тривиалли_* то наверное не обязательно

2020-07-08 09:33 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +    if (shared.buf->count > 1) {
Исправил

2020-07-08 09:35 UTC, AdvancerMan commented on bigint-optimized/optimized_storage.h
> +        T copy(e);
Я вроде как раз выделил случаи, когда копию `e` делать обязательно. То есть после этих строк идет иф, в результате которого обязательно произойдет копия `values`.

2020-09-17 18:51 UTC, kt-cpp approved these changes

2020-09-17 18:52 UTC, merged